apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-hms-config
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: metastore
type: Opaque
stringData:
  hive-site.xml:
    {{- include "hive-site" . | nindent 4 }}
  hive-env.sh:
    {{- include "hive-env-script" . | nindent 4 }}
