apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bookstack.fullname" . }}-data
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.catalogStorage | default "5Gi" }}

