apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hivemetastore.fullname" . }}-config
  labels:
    {{- include "hivemetastore.labels" . | nindent 4 }}
type: Opaque
stringData:
  hive-site.xml:
    {{- include "hive-site.xml" . | nindent 4 }}
  hive-env.sh: 
    {{- include "hive-env.sh" . | nindent 4 }}