apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-trino
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: trino
    subcomponent: coordinator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: trino
    subcomponent: coordinator

