FROM registry.gitlab.com/abyres/releases/centos8:8-1

ENV JAVA_VERSION=11 TINI_VERSION=0.19.0

ADD confluent.repo /etc/yum.repos.d/confluent.repo

RUN dnf install java-${JAVA_VERSION}-openjdk-headless confluent-schema-registry.noarch -y && \
    dnf clean all && \
    mkdir -p /opt/apache

ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /root/tini

RUN install -o root -g root -m 0755 /root/tini /usr/bin/tini

ENV JAVA_HOME=/usr/lib/jvm/jre-${JAVA_VERSION}/

ADD entrypoint.sh /opt/entrypoint.sh

EXPOSE 8081

ENTRYPOINT ["/usr/bin/tini", "/opt/entrypoint.sh"]
