apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-db
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: database
spec:
  clusterIP: None
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: database
