apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elixier.fullname" . }}-pgsql-createdb
  labels:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: database
    subcomponent: createdb
spec:
  completions: 1
  template:
    spec:
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      initContainers:
        {{- include "elixier.wait-db" . | nindent 8 }}
        - name: set-root-password
          image: "{{ .Values.kubectl_image.repository }}:{{ .Values.kubectl_image.tag }}"
          imagePullPolicy: {{ .Values.kubectl_image.pullPolicy }}
          args: ["exec", "-ti", '{{ include "elixier.fullname" . }}-db-0', "--",
                 "psql", "-c", "ALTER USER postgres PASSWORD '{{ .Values.pgsql.root_password }}';"]
      containers:
        - name: createdb-metastore
          image: "{{ .Values.kubectl_image.repository }}:{{ .Values.kubectl_image.tag }}"
          imagePullPolicy: {{ .Values.kubectl_image.pullPolicy }}
          args: ["exec", "-ti", '{{ include "elixier.fullname" . }}-db-0', "--",
                 "createdb_with_user.sh", "-d", "{{ .Values.hive.metastore_db_name }}", 
                 "-u", "{{ .Values.hive.metastore_db_user }}", "-p", "{{ .Values.hive.metastore_db_password }}"]
        - name: createdb-airflow
          image: "{{ .Values.kubectl_image.repository }}:{{ .Values.kubectl_image.tag }}"
          imagePullPolicy: {{ .Values.kubectl_image.pullPolicy }}
          args: ["exec", "-ti", '{{ include "elixier.fullname" . }}-db-0', "--",
                 "createdb_with_user.sh", "-d", "{{ .Values.airflow.db_name }}", 
                 "-u", "{{ .Values.airflow.db_user }}", "-p", "{{ .Values.airflow.db_password }}"]
        - name: createdb-superset
          image: "{{ .Values.kubectl_image.repository }}:{{ .Values.kubectl_image.tag }}"
          imagePullPolicy: {{ .Values.kubectl_image.pullPolicy }}
          args: ["exec", "-ti", '{{ include "elixier.fullname" . }}-db-0', "--",
                 "createdb_with_user.sh", "-d", "{{ .Values.superset.db_name }}", 
                 "-u", "{{ .Values.superset.db_user }}", "-p", "{{ .Values.superset.db_password }}"]
        - name: createdb-jupyterhub
          image: "{{ .Values.kubectl_image.repository }}:{{ .Values.kubectl_image.tag }}"
          imagePullPolicy: {{ .Values.kubectl_image.pullPolicy }}
          args: ["exec", "-ti", '{{ include "elixier.fullname" . }}-db-0', "--",
                 "createdb_with_user.sh", "-d", "{{ .Values.jupyterhub.db_name }}", 
                 "-u", "{{ .Values.jupyterhub.db_user }}", "-p", "{{ .Values.jupyterhub.db_password }}"]
      restartPolicy: Never
  backoffLimit: 10
