{{ if .Values.presto.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-presto-resmgr
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: presto
    subcomponent: resmgr
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: presto
    subcomponent: resmgr
{{- end }}
