apiVersion: v1
kind: Service
metadata:
  name: {{ include "schemaregistry.fullname" . }}-schemaregistry
  labels:
    {{- include "schemaregistry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "schemaregistry.selectorLabels" . | nindent 4 }}
