{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "trino.fullname" . }}
spec:
  rules:
  - host: trino.{{ .Values.global.ingressDomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "trino.fullname" . }}
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
    - secretName: {{ include "trino.fullname" . }}
      hosts:
      - trino.{{ .Values.global.ingressDomain }}
{{- end }}
