apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trino.fullname" . }}-cfg
  labels:
    {{- include "trino.labels" . | nindent 4 }}
type: Opaque
stringData:
  coordinator-config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    # discovery-server.enabled=false
    discovery.uri=http://{{ include "trino.fullname" . }}:8080
    # resource-manager-enabled=true
  resmgr-config.properties: |
    resource-manager=true
    resource-manager-enabled=true
    coordinator=false
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    thrift.server.port=8081
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
  worker-config.properties: |
    coordinator=false
    http-server.http.port=8080
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    discovery.uri=http://{{ include "trino.fullname" . }}:8080
    # resource-manager-enabled=true
  jvm.config: |
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    -XX:+UnlockDiagnosticVMOptions
    -XX:+UseAESCTRIntrinsics
    -Dcom.amazonaws.sdk.disableCertChecking=true
    -Dlogback.configurationFile=/opt/trino/etc/trino-ranger-plugin-logback.xml
  ranger-policymgr-ssl.xml: |
    {{ include "ranger-policymgr-ssl.xml" . | nindent 4 }}
  ranger-trino-audit.xml: |
    {{ include "ranger-trino-audit.xml" . | nindent 4 }}
  ranger-trino-security.xml: |
    {{ include "ranger-trino-security.xml" . | nindent 4 }}
  access-control.properties: |
    {{- if .Values.global.ranger.enabled }}
    access-control.name=ranger
    {{- else }}
    access-control.name=allow-all
    {{- end }}
  log.properties: 
    org.apache.ranger.authorization.trino.authorizer.RangerSystemAccessControl=DEBUG
