apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trino.fullname" . }}-w
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    component: worker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trino.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trino.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trino.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{ $Values := .Values }}
        {{ $Release := .Release }}
        {{- range .Values.waitContainers -}}
          {{$container := dict "Release" $Release "Values" $Values "Container" . }}
          {{- include "elixier.waitContainer" $container | nindent 8 }}
        {{- end }}
        {{- range .Values.waitDeployments -}}
          {{$container := dict "Release" $Release "Values" $Values "Container" . }}
          {{- include "elixier.waitDeployment" $container | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["run"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
          readinessProbe:
            httpGet:
              path: /v1/info
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/opt/trino/etc/config.properties"
              subPath: worker-config.properties
            {{ include "trino.volumeMounts" . | nindent 12 }}
            {{ include "elixier.volumeMounts" . | nindent 12 }}
      volumes:
        {{ include "trino.volumes" . | nindent 8 }}
        {{ include "elixier.volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ include "trino.name" . }}
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name }}
                    - key: component
                      operator: In
                      values:
                        - worker
                topologyKey: topology.kubernetes.io/zone
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
