apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opensearch.fullname" . }}-m
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    component: master
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "opensearch.fullname" . }}-m
  selector:
    matchLabels:
      {{- include "opensearch.selectorLabels" . | nindent 6 }}
      component: master
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opensearch.selectorLabels" . | nindent 8 }}
        component: master
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opensearch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "opensearch.volumes" . | nindent 8 }}

      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "opensearch.volumeMounts" . | nindent 12 }}
          env:
            {{- include "opensearch.env" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: binary
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 5
            periodSeconds: 15
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default "300" }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "opensearch.name" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
                  - key: component
                    operator: In
                    values:
                      - master
              topologyKey: topology.kubernetes.io/zone

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "opensearch.fullname" . }}-datadir
      spec:
        accessModes:
          - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
        {{ if .Values.storageClass -}}
        storageClassName: {{ quote .Values.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.instanceStorage | default "1Gi" }}

