apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-livy
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: livy
    subcomponent: server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 10000
      targetPort: livy
      protocol: TCP
      name: livy
    - port: 10001
      targetPort: livy2
      protocol: TCP
      name: livy2
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: livy
    subcomponent: server

