{{ if .Values.livy.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elixier.fullname" . }}-livy-spark-w
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: livy
    subcomponent: spark-worker
spec:
  serviceName: {{ include "elixier.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "elixier.selectorLabels" . | nindent 6 }}
      component: livy
      subcomponent: spark-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier.selectorLabels" . | nindent 8 }}
        component: livy
        subcomponent: spark-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "elixier.volumes" . | nindent 8 }}
        {{- include "elixier.livy.volumes" . | nindent 8 }}
      setHostnameAsFQDN: true
      initContainers:
        {{- include "elixier.wait-hms" . | nindent 8 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.livy_image.repository }}:{{ .Values.livy_image.tag }}"
          imagePullPolicy: {{ .Values.livy_image.pullPolicy }}
          args: ["/opt/apache/spark3/sbin/start-slave.sh", 'spark://{{ include "elixier.fullname" . }}-livy-spark-m:7077', '-p', '{{ .Values.spark.worker_port | default "33620" }}', '-c', "{{ .Values.spark.executor_cores }}", '-m', "{{ .Values.spark.executor_memory }}"]
          ports:
            - name: worker
              containerPort: {{ .Values.spark.worker_port | default "33620" }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.spark.worker_port | default "33620" }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.spark.worker_port | default "33620" }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            {{- include "elixier.volume-mounts" . | nindent 12 }}
            {{- include "elixier.livy.volume-mounts" . | nindent 12 }}
          env:
            {{- include "elixier.env" . | nindent 12 }}
            - name: SPARK_CONF_DIR
              value: /etc/livy-spark
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
