apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-secrets
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  minio_console_url: {{ include "elixier.minio.console_url" . | quote }}
  fernet-key: {{ quote .Values.secrets.fernet_key }}
  git-username: {{ quote .Values.airflow.dag_git_username }}
  git-password: {{ quote .Values.airflow.dag_git_password }}
  git-branch: {{ .Values.airflow.dag_git_branch | default "master" | quote }}
  s3a_access_key: {{ quote .Values.s3a.access_key }}
  s3a_secret_key: {{ quote .Values.s3a.secret_key }}
