{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-hadoop-config
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  core-site.xml: |
    {{- include "core-site" . | nindent 4 }}
