FROM registry.gitlab.com/abyres/releases/centos8:8-1

ENV TINI_VERSION=0.19.0

ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /root/tini

RUN install -o root -g root -m 0755 /root/tini /usr/bin/tini

ADD neo4j.repo /etc/yum.repos.d/neo4j.repo

ENV NEO4J_VERSION=4.4.18

RUN set -ex && \
    dnf install -y neo4j-$NEO4J_VERSION && \
    dnf clean all

RUN mkdir -p /etc/pki/neo4j

ADD server.key /etc/pki/neo4j/server.key
ADD server.crt /etc/pki/neo4j/server.crt

ENV NEO4J_CONF=/etc/neo4j NEO4J_HOME=/var/lib/neo4j

ADD entrypoint.sh /opt/entrypoint.sh

RUN chmod a+x /opt/entrypoint.sh

ENTRYPOINT ["/usr/bin/tini", "/opt/entrypoint.sh"]
