FROM registry.gitlab.com/abyres/releases/centos8:8-1

RUN dnf install git git-lfs git-subtree git-instaweb openssh-server gitweb sudo -y && \
    dnf clean all

RUN /usr/sbin/groupadd -r git --gid 1000 && \
     /usr/sbin/useradd -r -g git --uid 1000 \
     -m -d /home/git \
     -s /bin/bash git

ADD git-http.conf /etc/httpd/conf.d/git-http.conf
ADD entrypoint.sh /opt/entrypoint.sh
ADD newrepo.sh /usr/local/bin/newrepo
ADD gitweb.conf /etc/gitweb.conf
ADD sudoers /etc/sudoers.d/

RUN chmod a+rx /opt/entrypoint.sh && \
    chmod a+rx /usr/local/bin/newrepo && \
    mkdir /srv/git && \
    chown -R git:git /srv/git

ENV TINI_VERSION=0.19.0
ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /root/tini
RUN install -o root -g root -m 0755 /root/tini /usr/bin/tini

EXPOSE 22
EXPOSE 80
VOLUME /srv/git/

ENTRYPOINT ["/usr/bin/tini", "--", "sudo", "-E", "/opt/entrypoint.sh"]
