apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "drill.fullname" . }}
  labels:
    {{- include "drill.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "drill.fullname" . }}
  selector:
    matchLabels:
      {{- include "drill.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drill.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drill.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['run']
          ports:
            - name: user
              containerPort: 31010
              protocol: TCP
            - name: control
              containerPort: 31011
              protocol: TCP
            - name: data
              containerPort: 31012
              protocol: TCP
            - name: http
              containerPort: 8047
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "drill.fullname" . }}-datadir
              mountPath: "/var/lib/drill"
            - name: {{ include "drill.fullname" . }}-config
              mountPath: "/etc/drill"
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default "120" }}
      volumes:
        - name: {{ include "drill.fullname" . }}-config
          secret:
            secretName: {{ include "drill.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "drill.name" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: topology.kubernetes.io/zone
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "drill.fullname" . }}-datadir
      spec:
        accessModes:
          - {{ .Values.storageAccessMode | default "ReadWriteOnce" }}
        {{ if .Values.storageClass -}}
        storageClassName: {{ quote .Values.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.instanceStorage | default "5G" }}

