apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secrets
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  console_url: http://minio-console.{{ .Values.global.ingressDomain }}
  s3a_access_key: {{ quote .Values.global.s3a.accessKey }}
  s3a_secret_key: {{ quote .Values.global.s3a.secretKey }}