apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
    component: neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7474
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neo4j.selectorLabels" . | nindent 4 }}
