# vim: set filetype=dockerfile:

FROM fedora:37 AS extract

ENV LIVY_VERSION=0.8.0 JAVA_VERSION=1.8.0
WORKDIR /opt
RUN dnf install python3 python3-setuptools python3-pip \
    maven unzip git python-unversioned-command \
    java-${JAVA_VERSION}-openjdk-devel tar \
    bzip2 gzip -y && dnf clean all

ENV LIVY_REV=da246ff30d11705d8f9772950c34c4ae1c82cf09
RUN git clone https://github.com/apache/incubator-livy.git livy && \
    cd livy && git checkout $LIVY_REV

WORKDIR /opt/livy
RUN mvn clean package -B -V -e \
        -Pspark-3.0 \
        -DskipTests \
        -DskipITs \
        -Dmaven.javadoc.skip=true && \
    cp assembly/target/apache-livy-${LIVY_VERSION}-incubating-SNAPSHOT-bin.zip /output/
