# vim: set filetype=dockerfile:

FROM fedora:37 AS extract

ENV JAVA_VERSION=1.8.0
ENV CRAN_MIRROR="https://mirrors.upm.edu.my/CRAN/"

WORKDIR /opt
RUN dnf install python3 python3-setuptools python3-pip \
    maven unzip git python-unversioned-command \
    java-${JAVA_VERSION}-openjdk-devel tar \
    R-rmarkdown R-knitr R-devel \
    bzip2 gzip -y && dnf clean all && \
    Rscript -e "install.packages(\"e1071\", dep = TRUE, repos=\"${CRAN_MIRROR}\")"

ENV SPARK_VERSION=3.1.3 HADOOP_VERSION=3.2.3
ENV SPARK_RELEASENAME="elixier"
ENV JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}

RUN git clone https://github.com/apache/spark.git spark && \
    cd spark && git fetch --tags --all && \
    git checkout tags/v${SPARK_VERSION} -b ${SPARK_VERSION}

WORKDIR /opt/spark
RUN ./dev/make-distribution.sh --name ${SPARK_RELEASENAME} --pip --r --tgz -Psparkr \
    -Phive -Phive-thriftserver -Phadoop-cloud -Pyarn \
    -Pkubernetes -Dhadoop.version=${HADOOP_VERSION} -Dguava.version=20.0 && \
    mv spark-${SPARK_VERSION}-bin-${SPARK_RELEASENAME}.tgz /output/

WORKDIR /opt/
ENV LIVY_VERSION=0.8.0 
ENV LIVY_REV=da246ff30d11705d8f9772950c34c4ae1c82cf09

RUN dnf install patch -y && dnf clean all

RUN git clone https://github.com/apache/incubator-livy.git livy && \
    cd livy && git checkout $LIVY_REV 

WORKDIR /opt/livy
RUN mvn clean package -B -V -e \
        -Pspark-3.0 \
        -DskipTests \
        -DskipITs \
        -Dmaven.javadoc.skip=true && \
    mv assembly/target/apache-livy-${LIVY_VERSION}-incubating-SNAPSHOT-bin.zip /output/


