FROM fedora:37 as image

RUN dnf install -y python3 python3-requests \
    hostname openssl vim-enhanced bc procps-ng patch && \
    dnf clean all

ADD entrypoint.sh /usr/local/bin/entrypoint.sh
ADD create-service.py /opt/
RUN chmod +x /usr/local/bin/entrypoint.sh 

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
