FROM fedora:37 AS base

LABEL co.elixier.rev="0.0.1-1"

COPY dnf.conf /etc/dnf/dnf.conf

RUN dnf install dnf-plugins-core  -y && \
    dnf update -y && \
    dnf install -y bash iputils glibc-langpack-en net-tools \
        nmap bind-utils hostname nss pam wget \
        procps-ng vim-enhanced && \
    dnf clean all

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

ENV LC_ALL=en_US.utf8 \
    LANG=en_US.utf8 \
    PYTHONUNBUFFERED=1

FROM base AS superset

ENV PYTHON_VERSION=3.8 \
    SUPERSET_VERSION=2.0.1 \
    FLASK_APP="superset.app:create_app()" 

RUN /usr/sbin/groupadd -r user --gid 1000 && \
     /usr/sbin/useradd -r -g user --uid 1000 \
     -m -d /home/user \
     -s /sbin/nologin user

RUN dnf update -y && \
    dnf install -y mariadb-connector-c \
        postgresql-devel mariadb-devel \
        gcc-c++ cyrus-sasl-devel \
        perl-interpreter findutils git \
        "pkgconfig(python-${PYTHON_VERSION})" \
        /usr/bin/python${PYTHON_VERSION} \
        openldap-devel chromedriver \
        chromium && \
    dnf clean all

ADD requirements.txt /opt/
RUN /usr/bin/python${PYTHON_VERSION} -m venv /opt/elixier/superset/ && \
    /opt/elixier/superset/bin/pip install -r /opt/requirements.txt && \
    /opt/elixier/superset/bin/pip install "apache-superset"==${SUPERSET_VERSION} gevent && \
    mkdir -p /etc/superset /var/lib/superset /var/log/superset && \
    chown user:user -R /etc/superset /var/lib/superset /var/log/superset

ENV  TINI_VERSION=0.19.0 

ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /usr/bin/tini


ADD entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod a+x /usr/bin/entrypoint.sh /usr/bin/tini
WORKDIR /var/lib/superset/

ENV PYTHONPATH=/etc/superset \
    ACCESS_LOG=/var/log/superset/access.log \
    ERROR_LOG=/var/log/superset/errors.log \
    PYTHONUNBUFFERED=1 \
    LC_ALL=en_US.utf8 \
    LANG=en_US.utf8 \
    WEB_LISTEN_ADDRESS="0.0.0.0:8088" \
    CELERY_WORKERS=2 \
    WEB_WORKERS=10 \
    PATH="/opt/elixier/superset/bin:${PATH}" \
    DEFAULT_ADMIN="admin" \
    DEFAULT_ADMIN_PASSWORD="admin" \
    DEFAULT_ADMIN_EMAIL="admin@localhost.local" 


USER user

ENTRYPOINT ["/usr/bin/tini", "/usr/bin/entrypoint.sh"]
