{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: minio
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "elixier.fullname" . }}-minio
spec:
  rules:
  - host: minio.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "elixier.fullname" . }}-minio
            port:
              number: 9000
        path: /
        pathType: Prefix
  - host: minio-console.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "elixier.fullname" . }}-minio
            port:
              number: 9001
        path: /
        pathType: Prefix
  tls:
    - secretName: {{ include "elixier.fullname" . }}-minio
      hosts:
      - minio.{{ .Values.ingress.domain }}
    - secretName: {{ include "elixier.fullname" . }}-minio-console
      hosts:
      - minio-console.{{ .Values.ingress.domain }}
{{- end }}
