apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "elixier.fullname" . }}-createbucket
  labels:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: createbucket
spec:
  completions: 1
  template:
    spec:
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      initContainers:
        {{- include "elixier.wait-minio" . | nindent 8 }}
      containers:
        - name: createbucket 
          image: "{{ .Values.mc_image.repository }}:{{ .Values.mc_image.tag }}"
          imagePullPolicy: {{ .Values.mc_image.pullPolicy }}
          command: ["mc", "mb", "-p", "minio/warehouse", "minio/warehouse/tablespace", "minio/warehouse/event_log", "minio/filesystem"]
          env:
            - name: MC_HOST_minio
              value: 'http://{{ .Values.s3a.access_key }}:{{ .Values.s3a.secret_key }}@{{ include "elixier.fullname" . }}-minio:9000'
      restartPolicy: Never
  backoffLimit: 10
