apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-spark-config
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  spark-defaults.conf: |
    {{- include "spark-defaults" . | nindent 4 }}
  spark-env.sh: |
    {{- include "spark-env" . | nindent 4 }}
  hive-site.xml:
    {{- include "hive-site" . | nindent 4 }}
  beeline-hs2-connection.xml:
    {{- include "beeline-hs2-connection" . | nindent 4 }}
