FROM opensearchproject/opensearch:2.4.1

USER root
ENV TINI_VERSION=0.19.0

ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /root/tini

RUN install -o root -g root -m 0755 /root/tini /usr/bin/tini

USER $UID

ENTRYPOINT ["/usr/bin/tini",  "./opensearch-docker-entrypoint.sh"]
CMD ["opensearch"]
