ARG UID=5000
ARG GID=5000
FROM opensearchproject/opensearch:2.4.1
ARG UID
ARG GID
USER root
ENV TINI_VERSION=0.19.0

ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini /root/tini

RUN install -o root -g root -m 0755 /root/tini /usr/bin/tini

RUN chown -R ${UID}:${GID} /usr/share/opensearch

USER $UID

ENTRYPOINT ["/usr/bin/tini",  "--", "/bin/bash", "-x", "./opensearch-docker-entrypoint.sh"]
CMD ["opensearch"]
