{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-gitsecret
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.git.ssh_public_keys }}
  ssh_public_keys: {{ .Values.git.ssh_public_keys }}
{{- end }}
  gitweb_password: {{ .Values.git.gitweb_password }}
  gitweb_user: {{ .Values.git.gitweb_user }}
  gitweb_baseurl: {{ include "elixier.gitweb.baseurl" . }}
