apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}

