apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-jupyterhub-config
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  jupyterhub_config.py: |
    {{- include "jupyterhub-config" . | nindent 4 }}

