apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-s
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
