apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-config
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  server.properties: |
    {{- include "kafka-server-properties" . | nindent 4 }}
