apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}-s
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    component: kafka
    subcomponent: server
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "kafka.fullname" . }}-s
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}
      component: kafka
      subcomponent: server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka.selectorLabels" . | nindent 8 }}
        component: kafka
        subcomponent: server
    spec:
      setHostnameAsFQDN: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "kafka.volumes" . | nindent 8 }}

      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "kafka.volumeMounts" . | nindent 12 }}
          args: ['start']
          env:
            {{- include "kafka.env" . | nindent 12 }}
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
            - name: controller
              containerPort: 9093
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 10
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default "300" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ include "kafka.name" . }}
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: topology.kubernetes.io/zone
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "kafka.fullname" . }}-datadir
      spec:
        accessModes:
          - {{ .Values.storageAccessMode | default "ReadWriteMany" }}
        {{ if .Values.storageClass -}}
        storageClassName: {{ quote .Values.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.instanceStorage | default "1Gi" }}
