apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elixier.fullname" . }}-aflow-gs
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: airflow
    subcomponent: gitsync
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "elixier.selectorLabels" . | nindent 6 }}
      component: airflow
      subcomponent: gitsync
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier.selectorLabels" . | nindent 8 }}
        component: airflow
        subcomponent: gitsync
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "elixier.volumes" . | nindent 8 }}
      initContainers:
        {{- include "elixier.wait-gitweb" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gitsync_image.repository }}:{{ .Values.gitsync_image.tag }}"
          imagePullPolicy: {{ .Values.gitsync_image.pullPolicy }}
          args: ['--repo={{ include "elixier.airflow.dag_git_repository" . }}',
                 "--branch={{ .Values.airflow.dag_git_branch }}",
                 "--root=/var/lib/airflow/git",
                 "--dest=project", 
                 "--wait={{ .Values.airflow.dag_git_sync_wait | default 60 }}"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "elixier.volume-mounts" . | nindent 12 }}
          env:
            {{- include "elixier.env" . | nindent 12 }}
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "elixier.fullname" . }}-secrets
                  key: git-username
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "elixier.fullname" . }}-secrets
                  key: git-password
            - name: GIT_SYNC_BRANCH
              valueFrom:
                secretKeyRef:
                  name: {{ include "elixier.fullname" . }}-secrets
                  key: git-branch


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

