{{- if .Values.airflow.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "elixier.fullname" . }}-airflow-web
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "elixier.fullname" . }}-airflow-web
  minReplicas: {{ .Values.airflow.autoscaling.web.minReplicas }}
  maxReplicas: {{ .Values.airflow.autoscaling.web.maxReplicas }}
  metrics:
    {{- if .Values.airflow.autoscaling.web.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ .Values.airflow.autoscaling.web.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.airflow.autoscaling.web.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: {{ .Values.airflow.autoscaling.web.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
