{{- include "require" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elixier.fullname" . }}-aflow-s
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: airflow
    subcomponent: scheduler
spec:
  replicas: 1
  serviceName: {{ include "elixier.fullname" . }}-aflow-s
  selector:
    matchLabels:
      {{- include "elixier.selectorLabels" . | nindent 6 }}
      component: airflow
      subcomponent: scheduler
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elixier.selectorLabels" . | nindent 8 }}
        component: airflow
        subcomponent: scheduler
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "elixier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "elixier.volumes" . | nindent 8 }}
      initContainers:
        {{- include "elixier.wait-db" . | nindent 8 }}
        {{- include "elixier.wait-createdb" . | nindent 8 }}
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.core_image.repository }}:{{ .Values.core_image.tag }}"
          imagePullPolicy: {{ .Values.core_image.pullPolicy }}
          args: ["/opt/elixier/airflow/bin/entrypoint.sh", "first-init"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "elixier.volume-mounts" . | nindent 12 }}
          env:
            {{- include "elixier.env" . | nindent 12 }}

      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.core_image.repository }}:{{ .Values.core_image.tag }}"
          imagePullPolicy: {{ .Values.core_image.pullPolicy }}
          args: ["/opt/elixier/airflow/bin/entrypoint.sh", "scheduler"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "elixier.volume-mounts" . | nindent 12 }}
          env:
            {{- include "elixier.env" . | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

