apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nifi.fullname" . }}-config
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
data:
  state-management.xml: |
    {{- include "nifi.state-management" . | nindent 4 }}

  authorizers.xml: |
    {{- include "nifi.authorizers" . | nindent 4 }}
