{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "nifi.fullname" . }}
spec:
  host: {{ include "nifi.fullname" . }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8443
        tls:
          mode: SIMPLE
          insecureSkipVerify: true

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "nifi.fullname" . }}
spec:
  hosts:
    - "nifi.ezmeral.lan"
  gateways:
    - {{ .Values.istio.gateway }}
  http:
  - match:
      - uri: 
          prefix: /
    route:
      - destination:
          port:
            number: 8443
          host: {{ include "nifi.fullname" . }}
{{ end }}
