apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http

    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
