apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-redis
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: redis
