# vim: set filetype=dockerfile:

FROM fedora:37 AS builder

ENV JAVA_VERSION=11 RANGER_VERSION=2.3.0

RUN dnf install -y python3 java-${JAVA_VERSION}-openjdk-headless \
    maven java-${JAVA_VERSION}-openjdk-devel git tar bzip2 gzip libcloudproviders-devel openssl-devel gcc-c++ && \
    dnf groupinstall "Development Tools" -y && \
    dnf clean all

ENV JAVA_HOME=/usr/lib/jvm/jre-${JAVA_VERSION}/ OPENSSL_CONF=/dev/null \
    MAVEN_OPTS="-Dmaven.artifact.threads=30 -Dmaven.wagon.http.ssl.ignore.validity.dates=true -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"

ADD packages/elixier-ranger-${RANGER_VERSION}.tar.gz /opt/

WORKDIR /opt/ranger-elixier-ranger-${RANGER_VERSION}/

RUN mkdir -p /output/ && \
    mvn clean compile package install && \
    mvn eclipse:eclipse && \
    rm -rf /output/* && \
    mv target/* /output/

