FROM fedora:37 as extract

ENV RANGER_VERSION=2.3.0

ADD release/ranger-${RANGER_VERSION}-admin.tar.gz /opt/

FROM fedora:37 as image

ENV JAVA_VERSION=11 RANGER_VERSION=2.3.0 TRINO_VERSION=389

RUN dnf install -y python3 java-${JAVA_VERSION}-openjdk-headless \
    hostname openssl vim-enhanced postgresql-jdbc bc procps-ng patch && \
    dnf clean all

ENV JAVA_HOME=/usr/lib/jvm/jre-${JAVA_VERSION}/

RUN /usr/sbin/groupadd -r ranger --gid 1000 && \
     /usr/sbin/useradd -r -g ranger --uid 1000 \
     -m -d /home/ranger \
     -s /sbin/nologin ranger

COPY --chown=ranger:ranger --from=extract /opt/ranger-${RANGER_VERSION}-admin /opt/ranger-${RANGER_VERSION}-admin/
ADD release/ranger-${RANGER_VERSION}-migration-util.tar.gz /opt/
ADD release/ranger-${RANGER_VERSION}-tagsync.tar.gz /opt/
ADD release/ranger-${RANGER_VERSION}-usersync.tar.gz /opt/
ADD packages/trino-jdbc-${TRINO_VERSION}.jar /opt/ranger-${RANGER_VERSION}-admin/ews/webapp/WEB-INF/classes/ranger-plugins/trino/

WORKDIR /opt/ranger-${RANGER_VERSION}-admin/

ADD entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && mkdir /var/run/ranger && \
    chown ranger:ranger /var/run/ranger/

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
