{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: superset
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "elixier.fullname" . }}-superset
spec:
  rules:
  - host: superset.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "elixier.fullname" . }}-superset
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - secretName: {{ include "elixier.fullname" . }}-superset
      hosts:
      - superset.{{ .Values.ingress.domain }}

{{- end }}
