{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-superset-config
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  superset_config.py: |
    {{- include "superset-config" . | nindent 4 }}
  elixier_ss_custom.py: |
    {{- include "superset-custom-module" . | nindent 4 }}
