{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-superset-secrets
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.superset.admin_user }}
  admin-password: {{ .Values.superset.admin_password }}
  admin-email: {{ .Values.superset.admin_email }}
